packages:
  - '.'

allowBuilds:
  '@clerk/shared': true
  '@google/genai': true
  '@prisma/client': true
  '@prisma/engines': true
  '@reown/appkit': true
  '@stellar/stellar-sdk': true
  blake-hash: true
  bufferutil: true
  core-js: true
  es5-ext: true
  prisma: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true

overrides:
  hono: "4.12.25"
  "@codemirror/state": "^6.7.1"
  "@codemirror/view": "^6.43.6"
  "@codemirror/language": "^6.12.4"
