allowBuilds:
  '@clerk/shared': true
  '@prisma/client': true
  '@prisma/engines': true
  '@reown/appkit': true
  '@stellar/stellar-sdk': true
  blake-hash: true
  bufferutil: true
  core-js: true
  es5-ext: true
  prisma: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
